# Use official PostgreSQL 13 image as base image
FROM postgres:13

# Optional: Copy custom configuration or scripts
# COPY ./init.sql /docker-entrypoint-initdb.d/

# Optional: Set the environment variables directly in the Dockerfile (alternative to docker-compose)
# ENV POSTGRES_USER=root
# ENV POSTGRES_PASSWORD=root
# ENV POSTGRES_DB=ny_taxi
